import { Link } from "@tanstack/react-router";
import {
  AlertTriangle,
  BarChart3,
  Bot,
  CheckCircle2,
  ChevronRight,
  CircleDot,
  Clock3,
  Code2,
  Database,
  FileWarning,
  Filter,
  FlaskConical,
  GitBranch,
  Layout,
  MoreHorizontal,
  Plus,
  Import,
  RefreshCcw,
  Rocket,
  BookOpen,
  Search,
  Settings,
  ShieldCheck,
  Shield,
  SkipForward,
  Sparkles,
  XCircle,
} from "lucide-react";
import { useMemo, useState } from "react";
import { cn } from "@/lib/utils";

type TestStatus = "passed" | "failed" | "broken" | "skipped";
type Run = { id: string; branch: string; title: string; status: TestStatus; time: string; duration: string; total: number; passed: number; failed: number; broken: number; skipped: number };

const runs: Run[] = [
  { id: "run-4821", branch: "main", title: "Release verification", status: "failed", time: "12 min ago", duration: "8m 42s", total: 128, passed: 119, failed: 3, broken: 1, skipped: 5 },
  { id: "run-4820", branch: "feature/checkout", title: "Checkout regression", status: "broken", time: "38 min ago", duration: "6m 18s", total: 96, passed: 82, failed: 2, broken: 4, skipped: 8 },
  { id: "run-4819", branch: "main", title: "Nightly API suite", status: "passed", time: "2 h ago", duration: "11m 06s", total: 214, passed: 207, failed: 0, broken: 0, skipped: 7 },
  { id: "run-4818", branch: "hotfix/auth-timeout", title: "Authentication smoke", status: "passed", time: "3 h ago", duration: "2m 31s", total: 42, passed: 41, failed: 0, broken: 0, skipped: 1 },
  { id: "run-4817", branch: "main", title: "Frontend visual checks", status: "failed", time: "Yesterday", duration: "14m 03s", total: 167, passed: 154, failed: 6, broken: 0, skipped: 7 },
];

const tests = [
  { name: "Payment is confirmed after 3-D Secure", suite: "Checkout / Payment", status: "failed" as const, duration: "18.4s" },
  { name: "Refund is available for a completed order", suite: "Checkout / Refunds", status: "failed" as const, duration: "12.8s" },
  { name: "Discount is recalculated after cart change", suite: "Checkout / Pricing", status: "failed" as const, duration: "8.1s" },
  { name: "Customer receives order confirmation", suite: "Notifications", status: "broken" as const, duration: "0.7s" },
  { name: "Guest checkout preserves selected delivery", suite: "Checkout", status: "skipped" as const, duration: "—" },
];

const statusStyle: Record<TestStatus, string> = {
  passed: "bg-emerald-50 text-emerald-700 ring-emerald-600/20",
  failed: "bg-rose-50 text-rose-700 ring-rose-600/20",
  broken: "bg-amber-50 text-amber-800 ring-amber-600/20",
  skipped: "bg-slate-100 text-slate-600 ring-slate-500/20",
};
const statusText: Record<TestStatus, string> = { passed: "Passed", failed: "Failed", broken: "Broken", skipped: "Skipped" };
const StatusIcon = ({ status, className }: { status: TestStatus; className?: string }) => {
  const Icon = status === "passed" ? CheckCircle2 : status === "failed" ? XCircle : status === "broken" ? FileWarning : SkipForward;
  return <Icon className={className} />;
};

export function DemoPage() {
  const [activeSection, setActiveSection] = useState("Launches");
  const [view, setView] = useState<"overview" | "launches" | "launch" | "results" | "test" | "coverage" | "knowledge" | "settings">("launches");
  const [statusFilter, setStatusFilter] = useState<"all" | TestStatus>("all");
  const [selectedRun, setSelectedRun] = useState(runs[0]);
  const [selectedTest, setSelectedTest] = useState(tests[0]);
  const [analysisOpen, setAnalysisOpen] = useState(true);
  const visibleRuns = useMemo(() => statusFilter === "all" ? runs : runs.filter((run) => run.status === statusFilter), [statusFilter]);
  const navItems = [["Overview", Layout], ["Launches", Rocket], ["Coverage", Shield], ["Knowledge Base", BookOpen], ["Settings", Settings]] as const;
  const selectNav = (name: string) => {
    setActiveSection(name);
    setView(name === "Overview" ? "overview" : name === "Launches" ? "launches" : name === "Coverage" ? "coverage" : name === "Knowledge Base" ? "knowledge" : "settings");
  };

  return (
    <div className="demo-platform -mx-4 my-0 overflow-hidden border-x border-[#d9d0c4] sm:-mx-6 lg:-mx-8">
      <div className="flex min-h-[calc(100vh-9rem)] bg-[#faf8f5]">
        <aside className="hidden w-[20.5rem] shrink-0 flex-col border-r border-white/10 bg-[#172337] p-3 text-[#f2eee7] shadow-[28px_0_90px_rgba(9,16,30,0.28)] lg:flex">
          <div className="mb-6 flex items-start gap-3 px-3 py-2"><div className="grid h-12 w-12 place-items-center rounded-[1.1rem] border border-white/10 bg-white/10 text-sm font-bold tracking-[0.2em] text-white">VQ</div><div className="min-w-0 pt-1"><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-white/40">Project</p><button className="mt-1 flex items-center gap-1 text-sm font-medium text-white/80">Acme Store <ChevronRight className="h-3.5 w-3.5 rotate-90" /></button></div></div>
          <nav className="flex-1 space-y-1">{navItems.map(([name, Icon]) => <button key={name} onClick={() => selectNav(name)} className={cn("flex w-full items-center gap-3 rounded-[1rem] border px-3 py-3 text-left text-sm font-medium transition-all", activeSection === name ? "border-white/12 bg-white/15 text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.08)]" : "border-transparent text-white/60 hover:border-white/10 hover:bg-white/10 hover:text-white")}><Icon className="h-4 w-4" />{name}</button>)}</nav>
          <div className="rounded-[1rem] border border-white/10 bg-white/[0.035] px-3 py-2.5"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-white/85">Veriqorn</span><span className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-white/55">Demo</span></div></div>
          <div className="mt-3 flex items-center gap-3 rounded-[1.2rem] px-3 py-3 hover:bg-white/10"><div className="grid h-11 w-11 place-items-center rounded-full border border-white/10 bg-white/10 text-sm font-bold">AS</div><div><p className="text-sm font-semibold text-white">Alex Smith</p><p className="text-xs text-white/55">demo@veriqorn.io</p></div></div>
        </aside>

        <div className="min-w-0 flex-1">
          <main className="mx-auto w-full max-w-[1600px] p-4 md:p-6">
            <header className="relative overflow-hidden rounded-xl border border-[#d9d0c4] bg-white/95 px-6 py-6 shadow-[0_18px_50px_-28px_rgba(15,23,42,0.28)] sm:px-8"><div className="absolute inset-x-0 top-0 h-24 bg-[linear-gradient(90deg,rgba(7,166,184,0.12),rgba(248,128,88,0.12),transparent)]" /><div className="relative flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{["launch", "results", "test"].includes(view) && <button onClick={() => setView(view === "test" ? "results" : "launches")} className="mb-2 text-xs font-semibold text-[#16788a] hover:underline">← Back to {view === "test" ? "test results" : "launches"}</button>}<h1 className="text-3xl font-semibold tracking-tight text-[#172337]">{view === "launch" ? selectedRun.title : view === "results" ? "Test results" : view === "test" ? selectedTest.name : activeSection}</h1></div><div className="flex items-center gap-2"><span className="rounded-full border border-[#d9d0c4] bg-white px-3 py-1 text-xs font-medium text-slate-600">Acme Store</span><span className="rounded-full bg-emerald-600 px-3 py-1 text-xs font-semibold text-white">AI Pro</span><Link to="/" className="rounded-xl border border-[#d9d0c4] bg-white px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-[#f4ede4]">Exit demo</Link></div></div></header>
            <div className="mt-6 mb-5 rounded-xl border border-[#d9d0c4] bg-white/95 px-4 py-3 text-sm text-slate-600 shadow-[0_18px_50px_-28px_rgba(15,23,42,0.28)]"><span className="font-bold text-[#172337]">Demo workspace.</span> Explore freely — all launches, tests, and AI insights are simulated.</div>
            {view === "launches" ? <div>
            <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              <Metric label="Test health" value="93.0%" detail="+2.4% vs. last week" icon={ShieldCheck} tone="emerald" />
              <Metric label="Last launch" value="3 failed" detail="1 broken · 5 skipped" icon={AlertTriangle} tone="rose" />
              <Metric label="Mean duration" value="8m 36s" detail="12% faster this week" icon={Clock3} tone="cyan" />
              <Metric label="AI insights" value="4 new" detail="Root causes detected" icon={Sparkles} tone="violet" />
            </section>

            <div className="grid gap-6 2xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,0.85fr)]">
              <section className="overflow-hidden rounded-xl border border-[#d9d0c4] bg-white/95 shadow-[0_18px_50px_-28px_rgba(15,23,42,0.28)]">
                <div className="flex flex-col gap-3 border-b border-[#e8e0d7] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-[#172337]">Launches</h2><p className="mt-0.5 text-xs text-slate-500">Review and explore your test execution history.</p></div><div className="flex flex-wrap gap-2"><button className="inline-flex items-center gap-2 rounded-xl border border-[#d9d0c4] px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-[#f4ede4]"><Filter className="h-3.5 w-3.5" />Filters</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#16788a] px-3 py-2 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5" />Create launch</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#f4ede4] px-3 py-2 text-xs font-semibold text-[#172337]"><Import className="h-3.5 w-3.5" />Import results</button><button className="rounded-xl border border-[#d9d0c4] p-2 text-slate-500"><RefreshCcw className="h-3.5 w-3.5" /></button></div></div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-slate-400" />{(["all", "failed", "broken", "passed"] as const).map((filter) => <button key={filter} onClick={() => setStatusFilter(filter)} className={cn("rounded-lg px-2.5 py-1.5 text-xs font-semibold capitalize", statusFilter === filter ? "bg-[#16788a] text-white shadow-sm" : "border border-transparent text-slate-500 hover:border-[#d9d0c4] hover:bg-[#f4ede4]")}>{filter === "all" ? "All" : statusText[filter]}</button>)}</div></div>
                <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3 font-semibold">Launch</th><th className="px-3 py-3 font-semibold">Branch</th><th className="px-3 py-3 font-semibold">Result</th><th className="px-3 py-3 font-semibold">Tests</th><th className="px-3 py-3 font-semibold">Time</th></tr></thead><tbody>{visibleRuns.map((run) => <tr key={run.id} onClick={() => { setSelectedRun(run); setView("launch"); }} className={cn("cursor-pointer border-t border-slate-100 transition hover:bg-cyan-50/50", selectedRun.id === run.id && "bg-cyan-50/60")}><td className="px-4 py-3"><div className="font-semibold text-slate-800">{run.title}</div><div className="mt-0.5 font-mono text-xs text-slate-400">#{run.id.slice(4)}</div></td><td className="px-3 py-3"><span className="inline-flex items-center gap-1.5 text-xs text-slate-600"><GitBranch className="h-3.5 w-3.5" />{run.branch}</span></td><td className="px-3 py-3"><span className={cn("inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-bold ring-1 ring-inset", statusStyle[run.status])}><StatusIcon status={run.status} className="h-3.5 w-3.5" />{statusText[run.status]}</span></td><td className="px-3 py-3"><div className="font-semibold text-slate-700">{run.passed}/{run.total}</div><div className="text-xs text-slate-400">{run.failed ? `${run.failed} failed` : "all checked"}</div></td><td className="px-3 py-3 text-xs text-slate-500">{run.time}<div className="mt-0.5">{run.duration}</div></td></tr>)}</tbody></table></div>
              </section>

              <section className="rounded-xl border border-[#d9d0c4] bg-white/95 shadow-[0_18px_50px_-28px_rgba(15,23,42,0.28)]"><div className="flex items-center justify-between border-b border-[#e8e0d7] p-5"><div><h2 className="font-semibold text-[#172337]">Launch summary</h2><p className="mt-0.5 font-mono text-xs text-slate-500">#{selectedRun.id.slice(4)} · {selectedRun.branch}</p></div><MoreHorizontal className="h-5 w-5 text-slate-400" /></div><div className="grid grid-cols-4 divide-x divide-[#e8e0d7] border-b border-[#e8e0d7] text-center">{([['Passed', selectedRun.passed, 'text-emerald-600'], ['Failed', selectedRun.failed, 'text-rose-600'], ['Broken', selectedRun.broken, 'text-amber-600'], ['Skipped', selectedRun.skipped, 'text-slate-500']] as const).map(([label, value, tone]) => <div key={label} className="py-3"><div className={cn("text-lg font-bold", tone)}>{value}</div><div className="text-[10px] font-semibold uppercase text-slate-400">{label}</div></div>)}</div><div className="p-4"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold text-[#172337]">Needs attention</h3><span className="text-xs text-slate-400">{tests.length} tests</span></div><div className="space-y-1">{tests.map((test) => <button key={test.name} onClick={() => { setSelectedTest(test); setAnalysisOpen(true); }} className={cn("flex w-full items-center gap-3 rounded-xl p-2.5 text-left hover:bg-[#f8f4ef]", selectedTest.name === test.name && "bg-[#f8f4ef] ring-1 ring-[#d9d0c4]")}><StatusIcon status={test.status} className={cn("h-4 w-4 shrink-0", test.status === "failed" ? "text-rose-500" : test.status === "broken" ? "text-amber-500" : "text-slate-400")} /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-slate-700">{test.name}</span><span className="block truncate text-[11px] text-slate-400">{test.suite}</span></span><span className="text-[11px] text-slate-400">{test.duration}</span></button>)}</div></div></section>
            </div>

            {analysisOpen && <section className="mt-6 overflow-hidden rounded-xl border border-violet-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-violet-100 bg-violet-50/70 p-4"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-600 text-white"><Bot className="h-4 w-4" /></span><div><h2 className="text-sm font-bold text-violet-950">Veriqorn AI analysis</h2><p className="text-xs text-violet-700">Based on logs, history, and linked changes</p></div></div><button onClick={() => setAnalysisOpen(false)} className="text-xs font-semibold text-violet-700 hover:text-violet-950">Hide analysis</button></div><div className="grid gap-5 p-4 lg:grid-cols-[1.2fr_0.8fr]"><div><div className="mb-3 flex items-center gap-2"><StatusIcon status={selectedTest.status} className="h-4 w-4 text-rose-500" /><span className="font-semibold text-slate-800">{selectedTest.name}</span></div><p className="text-sm leading-6 text-slate-600">The payment confirmation API returned <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs text-rose-700">502 Bad Gateway</code> after the 3-D Secure redirect. This pattern first appeared in build #4818 and correlates with a change to the payment-provider client.</p><div className="mt-4 rounded-lg bg-slate-950 p-3 font-mono text-xs leading-5 text-slate-300"><span className="text-rose-300">POST</span> /api/payments/confirm → 502<br /><span className="text-slate-500">provider timeout after 15 000ms</span></div></div><div className="rounded-lg border border-violet-100 bg-violet-50/50 p-4"><div className="flex items-center gap-2 text-sm font-bold text-violet-950"><Sparkles className="h-4 w-4" />Likely root cause <span className="ml-auto rounded-full bg-violet-200 px-2 py-0.5 text-[10px]">87% confidence</span></div><p className="mt-2 text-sm leading-5 text-violet-900/80">The new retry configuration is not applied to the 3-D Secure callback request.</p><button className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-violet-700 hover:text-violet-950">View suggested fix <ChevronRight className="h-3.5 w-3.5" /></button></div></div></section>}
            </div> : <DemoSubPage view={view} run={selectedRun} test={selectedTest} onNavigate={setView} onTestSelect={(test) => { setSelectedTest(test); setView("test"); }} />}
          </main>
        </div>
      </div>
    </div>
  );
}

function DemoSubPage({ view, run, test, onNavigate, onTestSelect }: {
  view: "overview" | "launch" | "results" | "test" | "coverage" | "knowledge" | "settings";
  run: Run;
  test: (typeof tests)[number];
  onNavigate: (view: "overview" | "launches" | "launch" | "results" | "test" | "coverage" | "knowledge" | "settings") => void;
  onTestSelect: (test: (typeof tests)[number]) => void;
}) {
  const panel = "rounded-xl border border-[#d9d0c4] bg-white/95 p-5 shadow-[0_18px_50px_-28px_rgba(15,23,42,0.28)]";
  if (view === "overview") return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Metric label="Pass rate" value="93%" detail="+1.8% vs. previous period" icon={CheckCircle2} tone="emerald" /><Metric label="Flaky rate" value="2.8%" detail="-0.6% this week" icon={AlertTriangle} tone="rose" /><Metric label="Launches" value="48" detail="12 completed this week" icon={Rocket} tone="cyan" /></div><div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className={panel}><div className="flex items-center justify-between"><div><p className="eyebrow">Pass / fail trend</p><h2 className="mt-1 text-lg font-semibold text-[#172337]">Test execution trend</h2></div><button onClick={() => onNavigate("launches")} className="text-xs font-semibold text-[#16788a]">View launches →</button></div><TrendChart /></section><section className={panel}><p className="eyebrow">Latest run status</p><h2 className="mt-1 text-lg font-semibold text-[#172337]">Release verification</h2><DonutChart /><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="text-emerald-700">● 119 Passed</span><span className="text-rose-600">● 3 Failed</span><span className="text-amber-700">● 1 Broken</span><span className="text-slate-500">● 5 Skipped</span></div></section></div><div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><section className={panel}><div className="flex items-center justify-between"><h2 className="font-semibold text-[#172337]">Recent launches</h2><button onClick={() => onNavigate("launches")} className="text-xs font-semibold text-[#16788a]">Open all</button></div><div className="mt-4 divide-y divide-[#e8e0d7]">{runs.slice(0,3).map((item) => <button key={item.id} onClick={() => onNavigate("launch")} className="flex w-full items-center gap-3 py-3 text-left hover:bg-[#faf8f5]"><StatusIcon status={item.status} className="h-4 w-4 text-emerald-600" /><span className="flex-1"><b className="block text-sm text-[#172337]">{item.title}</b><span className="text-xs text-slate-500">{item.branch} · {item.time}</span></span><span className="text-xs text-slate-500">{item.passed}/{item.total}</span></button>)}</div></section><section className={panel}><p className="eyebrow">AI insight</p><div className="mt-4 flex gap-3"><Bot className="h-5 w-5 text-[#16788a]" /><p className="text-sm leading-6 text-slate-600">Payment failures correlate with the provider-client retry configuration introduced in build #4818.</p></div><button onClick={() => onNavigate("launches")} className="mt-5 text-sm font-semibold text-[#16788a]">Inspect evidence →</button></section></div></div>;
  if (view === "launch") return <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><section className={panel}><div className="flex items-start justify-between"><div><p className="eyebrow">Launch #{run.id.slice(4)}</p><h2 className="mt-2 text-xl font-semibold text-[#172337]">{run.title}</h2><p className="mt-1 text-sm text-slate-500"><GitBranch className="mr-1 inline h-3.5 w-3.5" />{run.branch} · completed {run.time}</p></div><span className={cn("inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold uppercase", statusStyle[run.status])}><StatusIcon status={run.status} className="h-3.5 w-3.5" />{statusText[run.status]}</span></div><div className="mt-7 grid grid-cols-4 divide-x divide-[#e8e0d7] rounded-xl border border-[#e8e0d7] text-center">{[["Passed",run.passed,"text-emerald-600"],["Failed",run.failed,"text-rose-600"],["Broken",run.broken,"text-amber-600"],["Skipped",run.skipped,"text-slate-500"]].map(([label,value,tone]) => <div key={String(label)} className="py-4"><b className={cn("text-xl", String(tone))}>{value}</b><p className="mt-1 text-[10px] font-semibold uppercase text-slate-400">{label}</p></div>)}</div><button onClick={() => onNavigate("results")} className="mt-6 rounded-xl bg-[#16788a] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#106676]">Open test results</button></section><section className={panel}><p className="eyebrow">Launch details</p><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between border-b border-[#e8e0d7] pb-3"><dt className="text-slate-500">Duration</dt><dd className="font-medium">{run.duration}</dd></div><div className="flex justify-between border-b border-[#e8e0d7] pb-3"><dt className="text-slate-500">Environment</dt><dd className="font-medium">staging</dd></div><div className="flex justify-between"><dt className="text-slate-500">Source</dt><dd className="font-medium">GitHub Actions</dd></div></dl></section></div>;
  if (view === "results") return <section className={panel}><div className="flex items-center justify-between"><div><p className="eyebrow">{run.title}</p><h2 className="mt-1 text-xl font-semibold text-[#172337]">Test results</h2></div><div className="rounded-xl border border-[#d9d0c4] px-3 py-2 text-xs text-slate-500"><Search className="mr-2 inline h-3.5 w-3.5" />Search results</div></div><div className="mt-6 divide-y divide-[#e8e0d7]">{tests.map((item) => <button key={item.name} onClick={() => onTestSelect(item)} className="flex w-full items-center gap-3 py-4 text-left hover:bg-[#faf8f5]"><StatusIcon status={item.status} className={cn("h-5 w-5", item.status === "failed" ? "text-rose-500" : item.status === "broken" ? "text-amber-500" : "text-slate-400")} /><span className="flex-1"><b className="block text-sm text-[#172337]">{item.name}</b><span className="text-xs text-slate-500">{item.suite}</span></span><span className="text-xs text-slate-400">{item.duration}</span><ChevronRight className="h-4 w-4 text-slate-400" /></button>)}</div></section>;
  if (view === "test") return <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><section className={panel}><div className="flex items-start gap-3"><StatusIcon status={test.status} className="mt-1 h-5 w-5 text-rose-500" /><div><p className="eyebrow">{test.suite}</p><h2 className="mt-1 text-xl font-semibold text-[#172337]">{test.name}</h2><p className="mt-1 text-sm text-slate-500">Failed in {test.duration}</p></div></div><div className="mt-7 rounded-xl bg-[#172337] p-4 font-mono text-xs leading-6 text-slate-200"><span className="text-rose-300">AssertionError:</span> expected payment status to equal "confirmed"<br /><span className="text-slate-500">at checkout/payment.spec.ts:184:21</span><br />received: "pending"</div><h3 className="mt-6 font-semibold text-[#172337]">Steps</h3><ol className="mt-3 space-y-2 text-sm text-slate-600"><li>1. Create a checkout session</li><li>2. Complete 3-D Secure authentication</li><li className="font-medium text-rose-600">3. Confirm payment — failed</li></ol></section><section className={cn(panel, "border-[#cfc5ee]")}><div className="flex items-center gap-2"><Bot className="h-5 w-5 text-[#16788a]" /><h2 className="font-semibold text-[#172337]">AI analysis</h2></div><p className="mt-4 text-sm leading-6 text-slate-600">The confirmation request timed out after the 3-D Secure callback. This aligns with a retry configuration change introduced in build #4818.</p><div className="mt-4 rounded-xl bg-[#f4ede4] p-3 text-sm text-[#172337]"><b>87% confidence</b><p className="mt-1">Check the provider-client retry policy.</p></div><button className="mt-4 text-sm font-semibold text-[#16788a] hover:underline">View suggested fix →</button></section></div>;
  if (view === "coverage") return <div className="space-y-4"><section className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-2xl font-semibold tracking-tight text-[#172337]"><Shield className="h-5 w-5" />Test coverage</h2><p className="mt-2 text-sm text-slate-500">Coverage intelligence over the platform's API, UI, and domain units — scored against the last 10 test runs.</p></div><div className="flex gap-2"><button className="rounded-xl border border-[#d9d0c4] px-3 py-2 text-xs font-semibold text-slate-600">Rebuild inventory</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#16788a] px-3 py-2 text-xs font-semibold text-white"><Sparkles className="h-3.5 w-3.5" />Generate recommendations</button></div></div></section><div className="grid gap-4 lg:grid-cols-[0.4fr_0.6fr]"><section className={panel}><p className="text-sm font-semibold text-[#172337]">Summary</p><p className="mt-1 text-xs text-slate-500">Project-wide coverage posture.</p><p className="mt-5 text-5xl font-semibold tracking-tight text-[#172337]">82.4</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">Coverage score (0–100)</p><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div><b className="block text-base">412</b>Units</div><div><b className="block text-base">339</b>Covered</div><div><b className="block text-base">91%</b>Confidence</div></div></section><section className={cn(panel, "p-0 overflow-hidden")}><div className="p-5"><p className="text-sm font-semibold text-[#172337]">Modules</p><p className="text-xs text-slate-500">Coverage score per module.</p></div><CoverageTable /></section></div><section className={cn(panel, "p-0 overflow-hidden")}><div className="p-5"><p className="text-sm font-semibold text-[#172337]">Top gaps</p><p className="text-xs text-slate-500">Units with low effective coverage, ordered by priority.</p></div><GapTable /></section></div>;
  const copy = view === "knowledge" ? ["Knowledge Base", "Ask your project", "Search indexed test documentation, repositories, and team knowledge."] : ["Settings", "Project settings", "Configure integrations, test result imports, and access for this project."];
  return <section className={panel}><p className="eyebrow">{copy[0]}</p><h2 className="mt-2 text-2xl font-semibold text-[#172337]">{copy[1]}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{copy[2]}</p><button className="mt-6 rounded-xl border border-[#d9d0c4] bg-white px-4 py-2.5 text-sm font-semibold text-[#172337] hover:bg-[#f4ede4]">Explore {copy[0]}</button></section>;
}

function TrendChart() {
  return <div className="mt-6"><svg viewBox="0 0 620 210" className="h-52 w-full" role="img" aria-label="Pass and fail trend"><defs><linearGradient id="passArea" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#10b981" stopOpacity=".25"/><stop offset="1" stopColor="#10b981" stopOpacity="0"/></linearGradient></defs>{[35,80,125,170].map((y) => <line key={y} x1="36" x2="600" y1={y} y2={y} stroke="#e8e0d7" strokeDasharray="3 5" />)}<path d="M36 155 L115 128 L195 139 L275 88 L355 106 L435 64 L515 79 L600 45 L600 190 L36 190 Z" fill="url(#passArea)"/><path d="M36 155 L115 128 L195 139 L275 88 L355 106 L435 64 L515 79 L600 45" fill="none" stroke="#10b981" strokeWidth="3"/><path d="M36 178 L115 171 L195 175 L275 157 L355 168 L435 146 L515 159 L600 137" fill="none" stroke="#ef4444" strokeWidth="3" strokeDasharray="6 5"/>{[36,115,195,275,355,435,515,600].map((x,i) => <text key={x} x={x} y="207" textAnchor="middle" fill="#78818c" fontSize="11">{`Jul ${18+i*2}`}</text>)}</svg><div className="flex gap-5 text-xs"><span className="text-emerald-700">━ Passed tests</span><span className="text-rose-600">┄ Failed tests</span></div></div>;
}

function DonutChart() {
  return <div className="mt-5 flex justify-center"><div className="relative h-36 w-36 rounded-full" style={{ background: "conic-gradient(#10b981 0 92.9%, #ef4444 92.9% 95.2%, #f59e0b 95.2% 96%, #94a3b8 96% 100%)" }}><div className="absolute inset-4 grid place-items-center rounded-full bg-white text-center"><b className="text-2xl text-[#172337]">93%</b><span className="text-[9px] font-semibold uppercase text-slate-500">pass rate</span></div></div></div>;
}

function CoverageTable() {
  const rows = [["checkout", "91.2", "83 / 91", "94%"], ["auth", "88.6", "54 / 61", "92%"], ["catalog", "76.1", "118 / 155", "89%"], ["notifications", "67.5", "84 / 105", "90%"]];
  return <table className="w-full text-sm"><thead className="bg-[#f4ede4] text-left text-xs font-semibold uppercase tracking-[.16em] text-slate-500"><tr><th className="px-4 py-3">Module</th><th className="px-4 py-3 text-right">Score</th><th className="px-4 py-3 text-right">Units</th><th className="px-4 py-3 text-right">Confidence</th></tr></thead><tbody className="divide-y divide-[#e8e0d7]">{rows.map((row) => <tr key={row[0]} className="hover:bg-[#faf8f5]"><td className="px-4 py-3 font-medium text-[#172337]">{row[0]}</td><td className="px-4 py-3 text-right">{row[1]}</td><td className="px-4 py-3 text-right">{row[2]}</td><td className="px-4 py-3 text-right">{row[3]}</td></tr>)}</tbody></table>;
}

function GapTable() {
  const rows = [["PaymentRetryPolicy", "checkout", "High", "34.0%", "Recent production path has no regression coverage"], ["OAuthCallback", "auth", "Medium", "48.2%", "Failure recovery path is untested"], ["TemplateRenderer", "notifications", "Medium", "52.0%", "Low test frequency in last 10 runs"]];
  return <table className="w-full text-sm"><thead className="bg-[#f4ede4] text-left text-xs font-semibold uppercase tracking-[.16em] text-slate-500"><tr><th className="px-4 py-3">Unit</th><th className="px-4 py-3">Module</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3 text-right">Coverage</th><th className="px-4 py-3">Reason</th></tr></thead><tbody className="divide-y divide-[#e8e0d7]">{rows.map((row) => <tr key={row[0]}><td className="px-4 py-3 font-medium text-[#172337]">{row[0]}</td><td className="px-4 py-3">{row[1]}</td><td className="px-4 py-3"><span className={cn("rounded-full px-2 py-1 text-xs font-semibold", row[2] === "High" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700")}>{row[2]}</span></td><td className="px-4 py-3 text-right">{row[3]}</td><td className="px-4 py-3 text-xs text-slate-500">{row[4]}</td></tr>)}</tbody></table>;
}

function Metric({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: typeof ShieldCheck; tone: "emerald" | "rose" | "cyan" | "violet" }) {
  const colors = { emerald: "bg-emerald-50 text-emerald-600", rose: "bg-rose-50 text-rose-600", cyan: "bg-cyan-50 text-cyan-600", violet: "bg-violet-50 text-violet-600" };
  return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{value}</p></div><span className={cn("grid h-9 w-9 place-items-center rounded-lg", colors[tone])}><Icon className="h-4 w-4" /></span></div><p className="mt-2 text-xs text-slate-500">{detail}</p></div>;
}
